### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Sph3x** [ESX-PUBLIC/esx_realweapons#1]
WEAPON_SMG
WEAPON_ASSAULTSMG
WEAPON_SNIPERRIFLE
and bat is going true your body

dont show on body 
i will test more

**Comment by Sph3x** [comment]
And it show weapons you dont have on you

**Comment by Sph3x** [comment]
So is it fixed since you close it

**Comment by renaiku** [comment]
Nope, you just didn't read the readme.
